export const INDUSTRY_LABELS: Record<string, string> = {
  information_technology: 'Information Technology',
  healthcare: 'Healthcare',
  finance: 'Finance',
  manufacturing: 'Manufacturing',
  education: 'Education',
  retail: 'Retail',
  transportation: 'Transportation',
  real_estate: 'Real Estate',
  construction: 'Construction',
  telecommunications: 'Telecommunications',
  energy: 'Energy',
  hospitality: 'Hospitality',
  entertainment: 'Entertainment',
  agriculture: 'Agriculture',
  automotive: 'Automotive',
  legal_services: 'Legal Services',
  aerospace_defense: 'Aerospace & Defense',
  logistics_supply_chain: 'Logistics & Supply Chain',
  public_sector_government: 'Public Sector / Government',
  non_profit_ngo: 'Non-Profit / NGO',
  media_publishing: 'Media & Publishing',
  food_beverage: 'Food & Beverage',
  pharmaceuticals: 'Pharmaceuticals',
  insurance: 'Insurance',
  ecommerce: 'E-Commerce',
  others: 'Others',
};
